// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY18e6eOe7dAmH448syBpp8RTVDvIkxYs',
    appId: '1:328159487670:web:70aa50abaa10d078f2e817',
    messagingSenderId: '328159487670',
    projectId: 'ielts-ai-study-assistant-8e0e0',
    authDomain: 'ielts-ai-study-assistant-8e0e0.firebaseapp.com',
    storageBucket: 'ielts-ai-study-assistant-8e0e0.firebasestorage.app',
    measurementId: 'G-LGCD7GNF4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaxSRhXl2OL8G9CATX_f7k3XsnmVHhetY',
    appId: '1:328159487670:android:c727109605ee0dc0f2e817',
    messagingSenderId: '328159487670',
    projectId: 'ielts-ai-study-assistant-8e0e0',
    storageBucket: 'ielts-ai-study-assistant-8e0e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4HmMIRajndrUS2-YQKattYxjGXP96_eY',
    appId: '1:328159487670:ios:c606440825681ff5f2e817',
    messagingSenderId: '328159487670',
    projectId: 'ielts-ai-study-assistant-8e0e0',
    storageBucket: 'ielts-ai-study-assistant-8e0e0.firebasestorage.app',
    iosBundleId: 'com.example.ieltsAiStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4HmMIRajndrUS2-YQKattYxjGXP96_eY',
    appId: '1:328159487670:ios:c606440825681ff5f2e817',
    messagingSenderId: '328159487670',
    projectId: 'ielts-ai-study-assistant-8e0e0',
    storageBucket: 'ielts-ai-study-assistant-8e0e0.firebasestorage.app',
    iosBundleId: 'com.example.ieltsAiStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY18e6eOe7dAmH448syBpp8RTVDvIkxYs',
    appId: '1:328159487670:web:271291902d0418f0f2e817',
    messagingSenderId: '328159487670',
    projectId: 'ielts-ai-study-assistant-8e0e0',
    authDomain: 'ielts-ai-study-assistant-8e0e0.firebaseapp.com',
    storageBucket: 'ielts-ai-study-assistant-8e0e0.firebasestorage.app',
    measurementId: 'G-KY9ZDNEKFC',
  );
}
